[[source]]
type = "manual"
version = "2" #this should be the same as the tag at dockerhub

[[source]]
type = "docker_hub"
namespace = "_"
image = "caddy"
tag = "2" #this should be the same as the tag at manual source

[[source]]
type = "github_tag"
repo = "caddy-dns/acmedns"

[tags]
version = true
semver = false

[config]
platforms = [
	"linux/386",
	"linux/amd64",
	"linux/arm/v6",
	"linux/arm/v7",
	"linux/arm64/v8",
	"linux/ppc64le",
	"linux/riscv64",
	"linux/s390x"
	]
