variables:
  PLATFORMS: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
  BUILDX_MAX_PARALLELISM: 4
  BADEG_VERSION_NAME: "stubby version"

include: https://gitlab.com/Lukas1818/gitlab-ci-template-docker/-/raw/main/Docker.gitlab-ci.yml
