name: Docker
on:
  push:
  
jobs:
  check-updates:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.outputs.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        id: "rust-toolchain"
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            targe
          key: "${{runner.os}} Rust ${{steps.rust-toolchain.outputs.cachekey}} Lock ${{hashFiles('Cargo.lock')}}"
      - run: cargo run
        id: outputs
        env:
          RUST_BACKTRACE: 1
          
  docker:
    runs-on: ubuntu-latest
    needs: [check-updates]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.check-updates.outputs.matrix) }}
    name: build '${{ matrix.path }}'
    steps:
      - name: Echo matrix
        run: |
          echo 'tag=${{ matrix.tag }}'
          echo 'path=${{ matrix.path }}'
          echo 'index=${{ matrix.index }}'
