name: Docker
on:
  push:
  
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"

  update:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.test.outputs.test }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        id: "rust-toolchain"
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            targe
          key: "${{runner.os}} Rust ${{steps.rust-toolchain.outputs.cachekey}} Lock ${{hashFiles('Cargo.lock')}}"
      - run: cargo run
        env:
          RUST_BACKTRACE: 1
      - run: cat output.txt >> $GITHUB_OUTPUT
        id: output
      - run: cat output.txt
      - run: echo "test=test" >> $GITHUB_OUTPUT
        id: test
      
  test:
    runs-on: ubuntu-latest
    needs: [update]
    steps:
      - name: Echo matrix
        run: echo "${{ needs.update.output.matrix }}"
      - name: test
        run: echo "${{ needs.update.outputs.test }}"
          
  docker:
    runs-on: ubuntu-latest
    needs: [update]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.update.output.matrix) }}
    steps:
      - name: Echo matrix
        run: |
          echo "${{ matrix.tag }}"
          echo "${{ matrix.path }}
