name: Docker
on:
  push:
  
jobs:
  update:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.test.output.test }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        id: "rust-toolchain"
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            targe
          key: "${{runner.os}} Rust ${{steps.rust-toolchain.outputs.cachekey}} Lock ${{hashFiles('Cargo.lock')}}"
      - run: cargo run
        env:
          RUST_BACKTRACE: 1
      - run: cat output.txt >> $GITHUB_OUTPUT
        id: output
      - run: cat output.txt
      - run: echo "matrix=test" >> $GITHUB_OUTPUT
        id: test
      
  test:
    runs-on: ubuntu-latest
    needs: [update]
    steps:
      - name: Echo matrix
        run: echo "${{ needs.update.output.matrix }}"
      - name: test
        run: echo "${{ needs.update.test.matrix }}"
          
  docker:
    runs-on: ubuntu-latest
    needs: [update]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.update.output.matrix) }}
    steps:
      - name: Echo matrix
        run: |
          echo "${{ matrix.tag }}"
          echo "${{ matrix.path }}
