[[source]]
type = "manual"
version = "1.4.18"

[[source]]
type = "docker_hub"
namespace = "_"
image = "debian"
tag = "stable-slim"

[tags]
version = true
semver = true

[config]
platforms = [
	"linux/386",
	"linux/amd64",
	"linux/arm/v7",
	"linux/arm64/v8",
	]
